### ISSUE TITLE
JINS MEMEスキャン時の挙動

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#100]
「基本設定」-「スキャン」を連続でタップすると、タップした回数だけスキャンと停止を繰り返します。また、スキャン時に「基本設定」画面から抜けてしまうと、少し時間が経ってから　BRIDGEが落ちます（スキャン停止と同じタイミングで落ちる気がします）。
検証時、JINS MEME本体は充電中（電源オフ）でした。

機種 : Xperia Z3 SGP611（タブレット）
OS : Android 6.0.1
アプリ : v0.8.3

**Comment by tkrworks** [comment]
連続スキャンできないように修正します。

**Comment by tkrworks** [comment]
次バージョンにて反映します。
