### ISSUE TITLE
Spotifyのアカウントを切り替えられない

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#101]
「Spotify」設定 - 「ログイン認証」にて、一度Spotifyにログインしてしまうと、項目右側のボタンをオフにしてもログインしたままになります。この状態で「Spotify」モードでプレイリスト選択すると、音楽が再生されてしまいます。
ボタンをオフにした状態でアプリを終了し、再度立ち上げると、ログインこそしていないのですが、ボタンをオンにすると同じアカウントでログインしてしまい、アカウントを切り替えられません。

**Comment by tkrworks** [comment]
バグと仕様の切り分けをしないとですね。

まず、アカウントを切り替えるためには、いったん、webブラウザでSpotifyのアカウント設定
に行って、そこからBRIDGEとのアプリ連携を解除する必要があります。

ログイン認証のスイッチがオフの場合に、カード選択で音が鳴ってしまうのはバグなので
修正します。

**Comment by tkrworks** [comment]
症状確認しました。

**Comment by tkrworks** [comment]
次バージョンで反映します。
