### ISSUE TITLE
EYE VDJカード内でのレイアウト崩れ

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#103]
EYE VDJカード内の「TRACKS5-8 」「FX」「LOGO」を選択すると、次の階層で最初に表示されるカードがそれぞれ「TRACKS6」「FX3」「LOGO4」となり、順番通りではなくなります。タップ操作時・MEMEでの操作時ともに確認しました。

機種 : Xperia Z3 SGP611（タブレット）
OS : Android 6.0.1
アプリ : v0.8.7

**Comment by tkrworks** [comment]
#50 と同じ問題と思われます。

**Comment by nariakiiwatani** [comment]
634c0be4397a74fa94f319c535d41951e7a5ca89
#105 と同様の対応を、同一メニュー内での階層移動についても行うようにして対処しました。

**Comment by tkrworks** [comment]
神対応ありがとうございます！
