### ISSUE TITLE
ポーズが勝手に解除されてしまう

### ISSUE THREAD

**Issue by mellowtronix** [jins-meme/JinsMemeBRIDGE-Android#104]
0.8.7　galaxyS7 edge android7.0
において
ポーズをかけたあと、１０秒程度で勝手に解除になってしまいます。

**Comment by nariakiiwatani** [comment]
再現できませんでした。
- MEME操作でも指操作でも起こるか
- MEMEとの通信を切った状態でも起こるか
- ポーズすると毎回起こるか
- 起こるまでの時間は毎回一定か
以上を報告していただけますか？

**Comment by tkrworks** [comment]
@mellowtronix 
v0.8.8で再現するか確認願います。

**Comment by mellowtronix** [comment]
0.8.7　galaxyS7 edge android7.0
指でやった時も起こってました
ポーズすると９割くらいの確率で起っていました
時間は一定ではありませんが短いと5秒くらい、長いと15秒くらいというイメージ

**Comment by mellowtronix** [comment]
0.9.1　NEXUS7 android7.0で確認
0.9.1　XPERIA SGP611 android6.0.1で確認

遅くなりました。
