### ISSUE TITLE
階層の下のメニューから戻る時にいつもカメラになってしまう

### ISSUE THREAD

**Issue by mellowtronix** [jins-meme/JinsMemeBRIDGE-Android#105]
0.8.7　galaxyS7 edge android7.0
において
たとえばspotifyなどのプレイリストメニューから「戻る」動作をすると
spotifyやhueとか、親階層ではなくてかならずカメラに行ってしまいます。

**Comment by nariakiiwatani** [comment]
カメラメニュー内（TAKE A PICTUREカードがある）の階層に行ってしまうという意味ですか？
そうではなくトップメニューに戻り、カメラカードが中央にある状態という意味ですと
https://github.com/jins-meme/JinsMemeBRIDGE-Android/issues/50
と同内容だと思われます。
内容の記述がわかりにくくてすみません。。

**Comment by mellowtronix** [comment]
言葉足らずですいません
たとえばspotifyなどの子階層(1-4プレイリストメニュー)から「戻る」動作をすると
spotifyの親階層ではなくて、かならず親階層カメラ(カメラアイコン)に行ってしまいます。
HUEの子階層(1-4+R)からから「戻る」動作をしても親階層のカメラアイコンにもどります。

**Comment by tkrworks** [comment]
これは仕様とし、クローズします。

**Comment by tkrworks** [comment]
間違えました・・・。

**Comment by nariakiiwatani** [comment]
8c1973f0b23b397ad313ced3bd37b7d87f65a475

メニュー遷移時に中央にあったカードを覚えておき、復帰時にその位置から始まるように修正しました。

**Comment by tkrworks** [comment]
確認しました。クローズします。
