### ISSUE TITLE
#104の関連　ポーズが解除されたあとしばらくするとカメラに戻る

### ISSUE THREAD

**Issue by mellowtronix** [jins-meme/JinsMemeBRIDGE-Android#106]
0.8.7　galaxyS7 edge android7.0
において
#104の関連　ですが
ポーズが解除されたあとも階層の低いメニューで作業していると
１０秒程度のうちに勝手にカメラトップメニューに持って行かれます。
たとえばirkitのセレクトメニューにいる時、ポーズをかけて解除すると
しばらくすると何もしてなくてもカメラのトップメニューになってしまうということです

**Comment by nariakiiwatani** [comment]
たぶんキャンセル操作が起こってますね。

@tkrworks 
4da18b5d22f47fc5927154feccafd17afc4881f8
この変更でキャンセル操作が判定されやすくなっている影響もあるかと思います。

@mellowtronix 
- 勝手にではなく自分でポーズを解除した場合も起こるか
- ポーズ->ポーズ解除をしない場合は起こらないか
以上を追加で調査お願いしたいです。

**Comment by tkrworks** [comment]
@mellowtronix 
v0.8.8で再現するか確認願います。

**Comment by mellowtronix** [comment]
v0.8.8　GALAXY7 ANDROID7
現在はおこらなくなりました
