### ISSUE TITLE
英語環境でJINS MEMEをスキャンするとUIが消える

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#118]
1. Android端末の言語設定を英語にする
2. BASIC - SCAN より MEME をスキャン
3. スキャン後、BASICから抜けると各UIが消える
4. BRIDGEを再起動すると各UI復活

機種 : Galaxy S7 Edge（スマホ）
OS : Android 7.0
アプリ : v0.9.5

**Comment by tkrworks** [comment]
正確には

1．Androidを英語にする
2．BASICに遷移
3．SCANをタップしMEMEのスキャンを開始
4．CONNECTで見つかったMEMEと接続
5．操作メニューに戻る
6．まっしろー

**Comment by tkrworks** [comment]
日本語でも起きる
