### ISSUE TITLE
英語メニューでMIDI設定には入れない

### ISSUE THREAD

**Issue by mellowtronix** [jins-meme/JinsMemeBRIDGE-Android#120]
sony xperia android 6.0.1 
NEXUS6 android 7.1.1

androidを英語表示にした状態で
BRIDGE APP基本設定から
MIDI (for Eye VDJ)を選択した時に
USBをMIDIに変更しても
USBをMIDIに変更してくださいと言われます。

**Comment by tkrworks** [comment]
こちらでは再現しません。

「Use USB to」の画面キャプチャとその状態になっている画面スクショもしくは
再現する流れのムービーを下さい。
