### ISSUE TITLE
視線操作と指操作の整合性

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#13]
このアプリの指操作を視線操作とどこまで合わせるか。

開発時に常にmemeをかけているよりも指で操作できる方が
開発効率が良いため、設定以外についても指での操作は
出来た方が良いが・・・。

**Comment by nariakiiwatani** [comment]
デバッグ機能としてならいくらでも指操作UI追加していいと思いますが、アプリに入れるべきかどうかについては協議必要ですよね。

指操作のためにボタンを追加して画面がごちゃごちゃするのは避けたいですが、ボタンがあることによってその画面でできることがみて取れるという利点もありますしね。
例えばカメラ画面だと、シャッターボタンが置いてあると一目でカメラ機能だとわかるとか。

**Comment by tkrworks** [comment]
現状、MEMEでpauseを有効にしても指操作でカードをスライドできてしまうため、
指操作も無効にしたい。また、指を使ってのpause処理の実装（画面をロングタップ？）
もしたいです。

**Comment by nariakiiwatani** [comment]
指操作でのpause解除操作は、画面タップですかね？

**Comment by tkrworks** [comment]
今、シングル・タップでカードの選択と、Fragmentの遷移になっているので
シングル・タップ以外が良いと思ってます。

操作のしやすさとしては、画面の長押し（ロングプレス？ロングタップ？）で
オンオフを切り替えられると良いと思います。

ダブルタップや、2本指タップなどは手の動きに不自由がある場合に難易度が
高くなってしまうので、避けたいです（視線操作前提ですが、MEMEの電池切れ
などで手で操作したい場合もあると思うので）。

**Comment by nariakiiwatani** [comment]
9265336b9d239d98b3555c13399eb129f3f414c8
修正しました。

ロングタップでポーズ/ポーズ解除。
ポーズ中は指操作、meme操作ともに、ポーズ解除以外の操作を無効にしました。

この修正に伴い、ついでにMemeでのキャンセルやポーズ操作の判定部分も整理しました。
memeRealtimeCallbackでカウントしていたのを、タイムベースで数えるようにしています。

**Comment by nariakiiwatani** [comment]
あ、すみませんなんかおかしいので再度修正します

**Comment by tkrworks** [comment]
ありがとうございます！確認出来ましたので、こちらクローズします。

**Comment by nariakiiwatani** [comment]
ありがとうございます。
追加の修正内容としては以下です。
・各Config内でもポーズ操作ができていた
-> Config内ではポーズ操作を無効にする
・ポーズ状態から戻るボタンでメニューを戻った際にポーズ表示のまま操作可能になっていた
-> 画面遷移時にポーズを強制解除

なお別のバグが発生しています。。
https://github.com/jins-meme/JinsMemeBRIDGE-Android/issues/80
