### ISSUE TITLE
ActionBarの戻るボタンを削除？

### ISSUE THREAD

**Issue by nariakiiwatani** [jins-meme/JinsMemeBRIDGE-Android#21]
e4b1d169d7895e688a5582a00ad0505afdb1bd64 でAndroidの戻るボタンが普通の（下記）動作をするように対応したのでActionBarの戻るボタンが不要になったかと思います。

- カードUIの階層をひとつずつ戻る
- 各種Configのスタックをひとつずつ戻る

**Comment by tkrworks** [comment]
ﾊﾞｰｼﾞｮﾝ0.6.12にてActionBarの戻るボタンを無くし、Androidの戻るボタンのみとしました。
