### ISSUE TITLE
戻るボタンをタップしたときの挙動

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#23]
戻ったときのカードの位置がひとつずれるようです。
以下、再現手順です。

1．midiをタップ
2．B4を表示
3．戻るをタップ
4．cameraになってる（midiになって欲しい）

1．midiをタップ
2．B4を表示
3．BASIC SETTINGに遷移
4．戻るをタップ
5．C4になってる（Ｂ4になって欲しい）

**Comment by nariakiiwatani** [comment]
ec7228b80e1bfcf023a9c68eded73c58cda79416 で対応済み
