### ISSUE TITLE
MenuFragmentの構造見直し

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#26]
基本機能部分と、Camera、Hue、VDJなどの外部制御機能部分がひとつのfragmentにまとまっているため、これらを分離し、コードの可読性、メンテ・デバッグ効率を良くしよー！

**Comment by nariakiiwatani** [comment]
MenuFragmentSeparationブランチにて作業中です。
各メニューはMenuFragmentBaseを継承したFragmentで、決定、右、左などの普通のMemeでのUI操作はMenuFragmentBaseに任せる設計にしています。
その関係で、MemeRealtimeListenerはMainActivityがimplementすることになっています。
それに伴い、ポーズとキャンセルの機能の詳細が変わっています。
満たすべき仕様は満たしていると思いますが、一度確認していただければと思います。

なお、2層目のUIについて左にスクロールできないバグ（初回表示時のみ）が発生しています。
これが解消したらmasterにマージしようと思います。

**Comment by nariakiiwatani** [comment]
ec7228b80e1bfcf023a9c68eded73c58cda79416 で完了
