### ISSUE TITLE
MenuFragmentのカードサイズが小さくなる。

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#3]
BasicConfigFragmentでソフトキーボードを開いたまま、MenuFragmentに戻ると、MenuFragmentのカードが小さくなってしまう。
今のところは、ソフトキーボードを先に閉じ、数十msecまってからMenuFragmentに戻るようにしているが、MenuFragment側で対処できると良いかも。

**Comment by nariakiiwatani** [comment]
https://github.com/jins-meme/JinsMemeBRIDGE-Android/commit/c940b4d6e1a1cfcdbf784dd044b30d8188874b90
camera_ntegrationブランチのこのコミットで、
MainActivity.java
activity_bridge_menu.xml
の修正でMenuFragmentをlayoutからでなくMainActivityのonCreateから作成するように修正しているんですが、おそらくこれで対処できるのではないかと思います。
このブランチ、masterにmergeして良いですか？master結構進んじゃったので手動でマージしたほうが早いかもしれませんが・・・。

**Comment by tkrworks** [comment]
カメラ機能部分マージ（もしくは、人力マージ）お願いしますー。

**Comment by nariakiiwatani** [comment]
実機がいま手元になく、シミュレーターでしか動作確認できなかったのでPRにしました。(#4)

**Comment by tkrworks** [comment]
修正されていることを実機で確認しましたー！
