### ISSUE TITLE
BridgeUIライブラリ部分とアプリケーション部分の分離

### ISSUE THREAD

**Issue by nariakiiwatani** [jins-meme/JinsMemeBRIDGE-Android#30]
6ea8080093e06ec2dcec49af5a8595864746f1f8
このコミットなんですが、各カードがどのような機能（画像があるとかテキストがあるとかテキストを書き換えられるとか）を持つかはアプリケーション側の都合であり、
オープンソースライブラリとしてのBridgeUIView.classのコードに含めるべきではないと思うのですがどうでしょう？

BridgeUIViewは開発者が自分のアプリを作るときに編集せずに使える形にしておきたいです。

**Comment by tkrworks** [comment]
BridgeUIViewは基本的に編集せず、というのは同意です。

現状、各FragmentにあるCardHolderを継承しているMyCardHolderの
中身がほぼ同じだったので、いったん今の状態をデフォルトとして
その処理をBridgeUIViewのCardHolderに入れてしまい、Fragment側を
スッキリさせられないかなーと思ってのコミットでした。

テンプレを用意するでしょうし、いったん、このコミットは元に
戻しますね。
