### ISSUE TITLE
VDJ以下に遷移した後の挙動

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#31]
1．EYE VDJを選択
2．TRACKS 1-4、TRACKS 5-8、FX、LOGOのどれかを選択
3．戻るボタン、キャンセル操作でトップに戻る
4．EYE VDJを選択
5．2で選択した階層を飛ばして最下層のカードが表示される

マージ時にミスった可能性あり・・・。

**Comment by nariakiiwatani** [comment]
戻るボタンの挙動、トップに戻るではなくてひとつ前の選択に戻るのつもりで作ってました。
どちらに修正しましょう？

**Comment by tkrworks** [comment]
一つ前に戻る、が良いと思います！

**Comment by nariakiiwatani** [comment]
2ea1b2a46e94112a201c116cf368a377132a475c で修正しました。
ついでに、以前話していた仕様の「戻るボタンやキャンセル操作ではアプリを終了させない」も入れてみました。

**Comment by tkrworks** [comment]
一つ前に戻る動作、確認しました。

> ついでに、以前話していた仕様の「戻るボタンやキャンセル操作ではアプリを終了させない」も入れてみました。

試してみたのですが、トップの階層で戻るボタンをタップするとアプリが落ちてしまいます。

**Comment by nariakiiwatani** [comment]
あ、すみません、戻るボタンだと終了できるようにしちゃってました。ボケてましたね・・・。

**Comment by nariakiiwatani** [comment]
落ちる問題は別でIssue立てましょうか。

**Comment by tkrworks** [comment]
そうしましょー
