### ISSUE TITLE
Hue Bridgeのボタンを押しても進まない

### ISSUE THREAD

**Issue by niimi** [jins-meme/JinsMemeBRIDGE-Android#37]
Found Hue Bridge. Please push the LINK Button...
のダイアログ時にBridgeのボタンを押しても進みません。
インビジにあるHueで再現しています。
公式アプリからは操作できました。

06-16 16:19:51.586 10129-10129/com.jins_meme.bridge D/DEBUG: HUE:: onAttach
06-16 16:19:51.677 10129-10129/com.jins_meme.bridge D/DEBUG: HUE:: onViewCreated
06-16 16:20:00.083 10129-10129/com.jins_meme.bridge D/DEBUG: item id = 4 HUE
06-16 16:20:00.083 10129-10129/com.jins_meme.bridge D/DEBUG: tap hue setting
06-16 16:20:00.257 10129-10129/com.jins_meme.bridge D/HUE: connectionState = 0
06-16 16:20:00.277 10129-10129/com.jins_meme.bridge D/DEBUG: Title = HUE SETTING
06-16 16:20:00.411 10129-10129/com.jins_meme.bridge D/HUE: index = 0
06-16 16:20:07.032 10129-10129/com.jins_meme.bridge D/HUE: swConnect = true
06-16 16:20:07.035 10129-10129/com.jins_meme.bridge D/HUE: search...
06-16 16:20:15.345 10129-10529/com.jins_meme.bridge D/HUE: Access Point Found... 1
06-16 16:20:15.357 10129-10529/com.jins_meme.bridge D/HUE: Access Point Found... 1
06-16 16:20:15.395 10129-10670/com.jins_meme.bridge D/HUE: Authentication Required...
06-16 16:20:15.401 10129-10670/com.jins_meme.bridge D/HUE: Authentication Required...
06-16 16:20:15.407 10129-10669/com.jins_meme.bridge D/HUE: Authentication Required...
06-16 16:20:15.409 10129-10669/com.jins_meme.bridge D/HUE: Authentication Required...
06-16 16:20:15.431 10129-10671/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:15.431 10129-10671/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:15.443 10129-10672/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:15.443 10129-10672/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:15.452 10129-10674/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:15.452 10129-10674/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:16.526 10129-10675/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:16.526 10129-10675/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:17.755 10129-10692/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:17.755 10129-10692/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:18.795 10129-10709/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:18.795 10129-10709/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:20.749 10129-10727/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:20.749 10129-10727/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:21.839 10129-10756/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:21.840 10129-10756/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:22.877 10129-10769/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:22.877 10129-10769/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:23.924 10129-10785/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:23.925 10129-10785/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:25.750 10129-10802/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:25.750 10129-10802/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:26.929 10129-10834/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:26.929 10129-10834/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:27.977 10129-10858/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:27.977 10129-10858/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 16:20:29.373 10129-10924/com.jins_meme.bridge D/HUE: Bridge Connected...
06-16 16:20:29.376 10129-10924/com.jins_meme.bridge D/HUE: setLastConnectIp
06-16 16:20:29.377 10129-10924/com.jins_meme.bridge D/HUE: Error Called : 42:Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
06-16 16:20:29.377 10129-10924/com.jins_meme.bridge D/HUE: Error Called : 42:Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
06-16 16:20:29.438 10129-10204/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 16:20:29.438 10129-10204/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 16:20:39.467 10129-10204/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 16:20:39.468 10129-10204/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 16:20:49.450 10129-10204/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 16:20:49.450 10129-10204/com.jins_meme.bridge D/HUE: Cache Updated...

**Comment by tkrworks** [comment]
Hueのバージョンが古いということはありませんか？

公式アプリもHueのファームによって二種類リリースされていたと思います。

**Comment by niimi** [comment]
ファームウェアの更新しましたが、同じ動作でした。
xyという値を取得する部分でエラーが起きているようです。

06-16 19:51:09.563 17086-17086/com.jins_meme.bridge D/BASIC: onViewCreated
06-16 19:51:09.568 17086-17086/com.jins_meme.bridge D/HUE: connectionState = 0
06-16 19:51:09.583 17086-17086/com.jins_meme.bridge D/DEBUG: Title = HUE SETTING
06-16 19:51:09.583 17086-17086/com.jins_meme.bridge D/DEBUG: false
06-16 19:51:09.608 17086-17091/com.jins_meme.bridge I/art: Do partial code cache collection, code=249KB, data=196KB
06-16 19:51:09.608 17086-17091/com.jins_meme.bridge I/art: After code cache collection, code=243KB, data=192KB
06-16 19:51:09.608 17086-17091/com.jins_meme.bridge I/art: Increasing code cache capacity to 1024KB
06-16 19:51:09.700 17086-17086/com.jins_meme.bridge D/HUE: index = 0
06-16 19:51:09.909 17086-17170/com.jins_meme.bridge D/OpenGLRenderer: endAllActiveAnimators on 0x71b05a2800 (MenuPopupWindow$MenuDropDownListView) with handle 0x71b35ee2a0
06-16 19:51:13.695 17086-17086/com.jins_meme.bridge D/HUE: swConnect = true
06-16 19:51:13.697 17086-17086/com.jins_meme.bridge D/HUE: search...
06-16 19:51:19.934 17086-17530/com.jins_meme.bridge D/HUE: Access Point Found... 1
06-16 19:51:19.946 17086-17530/com.jins_meme.bridge D/HUE: Access Point Found... 1
06-16 19:51:19.981 17086-17624/com.jins_meme.bridge D/HUE: Authentication Required...
06-16 19:51:19.983 17086-17624/com.jins_meme.bridge D/HUE: Authentication Required...
06-16 19:51:19.988 17086-17625/com.jins_meme.bridge D/HUE: Authentication Required...
06-16 19:51:19.991 17086-17625/com.jins_meme.bridge D/HUE: Authentication Required...
06-16 19:51:20.013 17086-17628/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:20.013 17086-17628/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:20.027 17086-17633/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:20.027 17086-17633/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:21.074 17086-17634/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:21.074 17086-17634/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:22.539 17086-17647/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:22.540 17086-17647/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:23.579 17086-17673/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:23.580 17086-17673/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:24.621 17086-17686/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:24.621 17086-17686/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:25.665 17086-17703/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:25.665 17086-17703/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:26.759 17086-17718/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:26.759 17086-17718/com.jins_meme.bridge D/HUE: Error Called : 101:link button not pressed
06-16 19:51:26.795 17086-17093/com.jins_meme.bridge W/art: Suspending all threads took: 12.966ms
06-16 19:51:26.830 17086-17188/com.jins_meme.bridge W/cr_BindingManager: Cannot setInForeground() - never saw a connection for the pid: 17086
06-16 19:51:28.233 17086-17752/com.jins_meme.bridge D/HUE: Bridge Connected...
06-16 19:51:28.237 17086-17752/com.jins_meme.bridge D/HUE: setLastConnectIp
06-16 19:51:28.238 17086-17752/com.jins_meme.bridge D/HUE: Error Called : 42:Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
06-16 19:51:28.238 17086-17752/com.jins_meme.bridge D/HUE: Error Called : 42:Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
06-16 19:51:28.340 17086-17166/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 19:51:28.340 17086-17166/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 19:51:38.331 17086-17166/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 19:51:38.331 17086-17166/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 19:51:48.349 17086-17166/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 19:51:48.349 17086-17166/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 19:51:58.338 17086-17166/com.jins_meme.bridge D/HUE: Cache Updated...
06-16 19:51:58.338 17086-17166/com.jins_meme.bridge D/HUE: Cache Updated...

**Comment by tkrworks** [comment]
ちなみに、動作する公式アプリはこれですよね？

https://play.google.com/store/apps/details?id=com.philips.lighting.hue2&hl=ja

**Comment by niimi** [comment]
そうです。アイコンがカラーの方です。

**Comment by tkrworks** [comment]
上記の症状、再現しました。
修正行います。
