### ISSUE TITLE
ConfigFragmentから戻るをタップしたとき

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#38]
下記のように設定メニューから次の設定メニューに遷移して、
戻るボタンをタップすると一つ前の設定メニューに戻った
ときにActionBarのタイトルが古いままとなります。

１．アプリ起動
２．BASICをタップ → BASIC SETTING
３．SPOTIFYをタップ → SPOTIFY SETTING
４．戻るボタンをタップ
５．BASICに戻るがタイトルがSPOTIFY SETTINGのまま
６．もう一度、戻るボタンをタップするとJINS MEME BRIDGEに戻る。

**Comment by nariakiiwatani** [comment]
8f79964385dd95caa42bd81354df7b6633e187ba
修正しました。

**Comment by tkrworks** [comment]
Rootにいる場合の修正は確認出来ましたが、Root以外、下記のような時に
まだ起きます。

1．Cameraカードをタップしてカメラ機能に遷移
2．Basicをタップし、Basic Settingsに遷移
3．戻るをタップ
4．カメラ機能に戻るが、タイトルはBasicSettingsのまま

**Comment by nariakiiwatani** [comment]
853bc4ceeff5c69e8b0ca7d77a7d6889e56976a4
修正しました。
各FragmentのonResumeで設定するようになっています。
現状、UI画面ではMenuFragmentBaseのonResumeで設定しているので、もしMenuFragmentBaseを継承していて別のタイトルを載せたい場合があればオーバーライドして設定すればうまくいくはずです。

**Comment by tkrworks** [comment]
ありがとうございます、確認しましたので、いったんクローズします。
