### ISSUE TITLE
Fragmentが複数重なる

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#39]
イジワルテストになってますが・・・
例えば

1．Cameraカードをタップ
2．Fragmentが切り替わる前にすばやく再度Cameraカードをタップ
3．CameraMenuFragmentが2枚になってしまう。
4．戻るボタンをタップするとまたCameraMenuFragmentになる

となります。

添付のmp4はカードのタップと戻るボタンを交互？にタップしたものです。

[IMG_3338.zip](https://github.com/jins-meme/JinsMemeBRIDGE-Android/files/1083722/IMG_3338.zip)

**Comment by nariakiiwatani** [comment]
カメラだけでなく、他全てのメニューで再現可能でした。
また、BridgeUIViewのインスタンスが切り替わらない場面（EYE VDJのTRACKS -> TRACK）でも同様の問題が起きています。

対処法検討中です。

**Comment by tkrworks** [comment]
レアケースのため一旦クローズします。
