### ISSUE TITLE
IRKitのカード選択できたか分からない

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#41]
IRKit以下のカードをタップ、瞬目で選択したときに
画面変化がないので、選択されたのかどうかが
分かりません。

IRKitで正しく操作できなかったときに、IRKitの設定などに
問題があるのか、MEMEとの通信に問題があるのかが今の
ままだと分からないので、選択したときの画面変化が
欲しいです。

**Comment by niimi** [comment]
結果を表示するようにしました
f748b6156dc72e4c0b5cee83f055c1b86afbc7a6

**Comment by tkrworks** [comment]
修正確認出来たのでクローズします。
