### ISSUE TITLE
TAKE A PICTUREタップ時のToast表示

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#44]
「TAKE A PICTURE」を連続してタップしまくると
表示されたToastが消えるまでに時間がかかる。

**Comment by nariakiiwatani** [comment]
e51f40c9704e9949aa520731001369d05a9536b6
次のを表示するときに、前のをcancelするように修正しました。
フェードアウトアニメの分があるのでやっぱり渋滞はしますが、だいぶ緩和したと思います。

**Comment by tkrworks** [comment]
改善されていること、確認出来ましたのでクローズします。
