### ISSUE TITLE
IRKitのSIGNALカードの連打

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#46]
SIGNALカードを連打しまくると、それ以降、カードをタップしても
IRKitのStatus LEDが反応しなくなる（通常、青LEDが数回点滅するが、
点滅しない）。

何度かタップしてるとたまに反応（数タップに1回程度）していたが、
その後はまったく反応しなくなり、勝手にIRKitの再起動がかかった。

IRKitがアプリからのコマンド？を正常に受けて、家電に対して
リモコン信号を送り終わるまでは、その途中できたタップ操作は
無視した方が良いかもです。

**Comment by niimi** [comment]
レスポンスが帰ってくるまで送らないようにしました。
