### ISSUE TITLE
IRKitの表記

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#58]
設定メニューの表記が頭のIが小文字のiでiRKitとなっています。
たぶん頭大文字が正解なので、修正願います。

**Comment by niimi** [comment]
これって、緑色になったり赤色になったりする部分のことでしょうか？

**Comment by tkrworks** [comment]
はい、そうですー

**Comment by niimi** [comment]
この部分はデバイスから取得できる文字を表示しているんですが、大塚さんに確認したところ大文字になったり小文字になったりするようです。

**Comment by tkrworks** [comment]
了解ですー。
こちら側でどうこうすることでは無いようなので、クローズします。
