### ISSUE TITLE
カードの左移動

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#6]
MenuFragmentのカードの右移動については、エンドレスに循環しますが、左移動については循環しない（例えば、アプリ起動直後、MIDIと表示されている状態でカードを左に送ろうとしても送れない。）です。

左方向も可能であれば循環した方が「あれ？左が効かない？」という混乱が生じないと思います。ここって循環させない理由あるんでしたっけ？

**Comment by nariakiiwatani** [comment]
basecampで報告してるやつですが、メニューを再生成すると初期化がうまくいかないバグがあり、未対応です。
CameraFragmentに移行するときのように、Fragmentをreplaceでなくhideすると問題なくなるのですがどう対応したものか…というところですね。

2017年5月14日(日) 22:57 Shunichi Yamamoto <notifications@github.com>:

**Comment by tkrworks** [comment]
報告して頂いてた問題と関連してたんですね・・・。

https://github.com/jins-meme/JinsMemeBRIDGE-Android/commit/cd15a257f273a2957ead2dcebff0b8e5e6a77776

仮でCameraFragmentへの遷移をMainActivityで行うようにしてみました。
挙動的には問題無さそうですが、確認してみて下さい。

**Comment by nariakiiwatani** [comment]
なんか誤解がありそうなので問題を整理します。

---
- 問題  
MenuFragmentで生成しているBridgeUIViewが左端から始まってしまうので左にスクロールできない

- 原因  
MenuFragment（もしくはBridgeUIView?）が一度破棄されて再度生成されると、必要なタイミングでCardLayoutManager.onLayoutCompletedが呼ばれず、スクロールの初期位置（中央）へ移動されない

- 再現手順  
アプリ起動後に設定画面等、他のFragmentに移行（replace）してから戻ってくると発生（アプリ起動直後は問題なし）

>（例えば、アプリ起動直後、MIDIと表示されている状態でカードを左に送ろうとしても送れない。）

これについてはこちらで確認できませんでした。

- CameraFragmentで入れていた対処  
MenuFragmentをreplaceすると戻ってきたときに再生成されて問題が発生してしまうので、hideする

---

cd15a25の修正では、CameraFragmentへの移行時にもreplaceを使うように変更されているので、同様の問題が起こっています。
対処としては、アプリ全体でMenuFragmentを破棄しない作りにするか、正しく再生成されるようにバグの原因を探して修正するかだと思われます。

**Comment by tkrworks** [comment]
すいません、思いっきり誤解してました・・・。

**Comment by tkrworks** [comment]
・アプリ起動直後、MIDIと表示されている状態でカードを左に送ろうとしても送れない。

ですが、Android 7系（Google Nexus6P(7.1.2)、Motorola Moto Z(7.0)）だと発生し、6系(Blackberry Priv(6.0.1))だと発生しませんでした。

**Comment by tkrworks** [comment]
Android 6での再現方法見つけました。

1．アプリ起動
2．右上設定アイコンからBASICに移動。
3．左上矢印もしくはOSの戻るボタンで戻る
4．画面スライドで左にいかない

**Comment by tkrworks** [comment]
Android 7系だと起動直後でも発生しました。

**Comment by nariakiiwatani** [comment]
なるほど・・・。
いろいろ調査ありがとうございます。
対処考えて見ます。

**Comment by tkrworks** [comment]
Issues #5 への対応を実装していて、mView.reset()を呼ぶと左方向への循環が
出来るようになったので、スマートかは別として実装してみました。

testブランチの最新（v0.6.8）で動作確認出来ます。

**Comment by nariakiiwatani** [comment]
ありがとうございます！
reset呼ぶのは試してダメだった記憶があるんですが、呼ぶタイミングが違うのがうまく働いているのかもしれませんね。

動作確認したんですが、まだ起こることがありそうですね。。
まだエミュレータでしか確認できてないんですが、Nexus 5 API 23で

- Basic Settings -Back-> Camera -back-> 
- About -Back-> Camera -back-> 
- MIDI Settings -(Warning)-OK->

以上の遷移で再発しました。
ただしどれも100%ではなく、30〜50%くらいの割合で発生してしまうように見えます。

以前よりだいぶ良いのでmasterにmergeして良いと思いますが、引き続き調査します。

**Comment by tkrworks** [comment]
> - Basic Settings -Back-> Camera -back->
> - About -Back-> Camera -back->
> - MIDI Settings -(Warning)-OK->
> 
> 以上の遷移で再発しました。

3つ目のMIDI Settingからのはreset呼び忘れでした。
上2つは実機デモ発生確認出来ました。これらはもうちょい再現方法・手順を
調査しないとですね・・・。

**Comment by nariakiiwatani** [comment]
closeしてしまいましたがこれ忘れてました。未確認なのでreopenしておきます。

> Android 7系だと起動直後でも発生しました。

**Comment by tkrworks** [comment]
Android 7系での動作も確認出来ましたので、クローズします。

**Comment by tkrworks** [comment]
MenuFragmentSeparationブランチの変更をTestブランチにマージしているのですが、
Android7.0にてアプリ起動直後に左移動出来ない現象が出ました。

アプリ起動直後は100％再現します。Android 6.0では問題なしです。

**Comment by tkrworks** [comment]
https://github.com/jins-meme/JinsMemeBRIDGE-Android/commit/2f41cf5454f508fa32f36c46630d988afe2b58b5 でAndroid7で修正確認出来たのでクローズします。
