### ISSUE TITLE
バックグラウンドから復帰時のカメラ映像

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#61]
1．カメラのカードを選択し、CameraMenuFragmentに遷移
2．カメラの映像が見えている状態でホームボタン「○」を
　　タップしアプリをバックグラウンドにうつす
3．マルチタスクボタン「□」をタップし、アプリをバック
　　グラウンドから復帰させる
4．カメラの映像を映してるViewが真っ暗
5．いったん、戻るボタン「◁」でRootに戻ってから
　　再度、カメラに行くと問題無く映像が映し出される。

**Comment by nariakiiwatani** [comment]
cf2f81bef08466e03d804b5e4b7af973ff52cab1
修正しました。

**Comment by tkrworks** [comment]
修正確認しました。クローズします。
