### ISSUE TITLE
設定メニュー内TextViewのフォーカス

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#66]
TextFieldにフォーカスが当たっている時にTextFieldの外、何も
無い箇所をタップするとTextのフォーカスがはずれるが、
ボタン等をタップしたときにはフォーカスが残る。

TextFieldを使っている以下のConfigFragmentは、ボタン等を
タップしたときもフォーカスが外れるように修正を行う。

IRKit / Nature Remo
OSC (for Eye VDJ)

**Comment by niimi** [comment]
irkit実装しました
43f70e2c809df275af705ee7e34aec16df76b9fe
