### ISSUE TITLE
HUE設定メニュー HUEの見つからない状態でCONNECTするとキャンセルできない

### ISSUE THREAD

**Issue by mellowtronix** [jins-meme/JinsMemeBRIDGE-Android#67]
HUE設定メニュー HUEの見つからない状態でCONNECTすると検索のままになり
抜けられないため、CANCELなどが必要だと思います。

**Comment by tkrworks** [comment]
タイムアウトするようにしました。
確認下さい。

**Comment by tkrworks** [comment]
クローズされず、放置されてるので、僕の方でクローズします。
再度、同様の問題が出る場合にはリオープンして報告願います。
