### ISSUE TITLE
HUE SETTINGメニューの左上のLIGHTナンバー

### ISSUE THREAD

**Issue by mellowtronix** [jins-meme/JinsMemeBRIDGE-Android#68]
HUE SETTINGメニューにおいて
右上のLIGHTメモリセレクトを変更しても
の左上のLIGHTナンバーがかわりません。
例えばLIGHT3を設定で選んでも
LIGHT1のままの表示になっています。

**Comment by tkrworks** [comment]
確認しました、修正しますー

**Comment by tkrworks** [comment]
設定メニューのレイアウト変更に伴い、このTextViewを削除したのでクローズします。
