### ISSUE TITLE
spotify プレイリスト再生バグ

### ISSUE THREAD

**Issue by ayakooo** [jins-meme/JinsMemeBRIDGE-Android#72]
プレイリストが複数かぶって再生される。
（プレイリストを１つ選択して更に他を再生すると同時再生となる。）

**Comment by tkrworks** [comment]
Androidのバージョン、Spotifyの設定メニューの状態を教えて下さい。

**Comment by mellowtronix** [comment]
spotifyの関係をすこしここにまとめます。
上記一旦忘れてください。(この現象起こったのが一回だけなので)


spotify設定メニュー不具合　

Version0.7.4 (galaxy7　android 7.0)において
bridge立ち上げmeme接続をした後spotify設定に行き、

spotify設定画面で
・前回設定したプレイリストを設定して
一度メインインターフェースに戻ってもう一度
spotify設定に行くと
プレイリストのメニュー(ユーザープレイリスト、spotifyプレイリストetc)
は表示されているが、そのサブメニュー(たとえばspotifyのプレイリストならsummer hitsなど)
が表示されていない

また、
最初にプレイリストを選ぶときに一回触っただけでは
サブメニューは表示されず、
一度他のプレイリストメニュー(ユーザープレイリスト、spotifyプレイリストetc)
を選んでサイド他のプレイリストメニューに切り替えないと
サブプレイリストメニューが表示されてこない様です

ちなみに現状は再生できません。

**Comment by tkrworks** [comment]
Spotifyの問題であっても、上記のように複数のバグをここにまとめることはしないで下さい。
また、テストで使用したバージョンが0.7.4とのことですが、0.7.5がreleaseページに上げてあった
と思いますので、必ず最新版でテストを行うようにして下さい。

上の不具合は0.7.5で修正済みです。

**Comment by tkrworks** [comment]
クローズされず、放置されてるので、僕の方でクローズします。
再度同じ症状が確認されるようならリオープンして報告願います。
