### ISSUE TITLE
カメラ機能「TAKE A PICTURE」タップ時の挙動

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#78]
Android6系で確認した事象です。

カメラ機能で「TAKE A PICTURE」を1回タップしたときに写真が
2枚撮影及び保存されることがあります。

確実な再現方法が分からないのですが、現象としては

1．「TAKE A PICTURE」をタップ
2．写真を保存しました・・・のToastが表示される
3．カメラのフォーカス？がちょっと動く
4．再び写真を保存しました・・・のToastが表示される

となります。

**Comment by nariakiiwatani** [comment]
c4a55077218df1d20fa80a9e08de8ec7b61808e4
修正しました。
オートフォーカスの終了を待つ処理でステートがなんらかロックされてしまって待ち続けるバグがあったのでそれの対処として
「オートフォーカスのステートがおかしかったらとりあえず撮影する」を入れていたのですがその影響と思われます。
待ち続ける問題が再発している可能性がありますが、とりあえずこのIssueへの対処は完了です。

**Comment by nariakiiwatani** [comment]
c6073c29a29519f426f9a2bb8418a91df9db664d
すみませんこちらでご確認ください。

**Comment by tkrworks** [comment]
修正を確認しました。クローズします！
