### ISSUE TITLE
codeStyleSettings.xmlの内容が実際に適用されているルールと違う

### ISSUE THREAD

**Issue by nariakiiwatani** [jins-meme/JinsMemeBRIDGE-Android#8]
@tkrworks ご確認の上codeStyleSettings.xmlを更新お願いできますか？

**Comment by tkrworks** [comment]
https://github.com/jins-meme/JinsMemeBRIDGE-Android/commit/bc547c0cf69151caa699382341cb776bc597f3d4
https://github.com/jins-meme/JinsMemeBRIDGE-Android/commit/9f01e8cc2f252d15e6c9fdfb18862812787f4c8d

これで大丈夫だと思いますが、もしきちんと反映されてなければ

Settings → Editor → Code Style → Java

でSchemeのところのmanageでGoogleStyle.xmlをimportして下さい。
