### ISSUE TITLE
galaxy7　インターフェースが固まる

### ISSUE THREAD

**Issue by mellowtronix** [jins-meme/JinsMemeBRIDGE-Android#85]
0.7.4  galaxy7　android7.0において
メインのインターフェースを左右にスワイプ(指で)
していると、高確率でちょっと暗い画面になってロックみたいなのがかかります
不思議なのはメニューは生きてて
メニューなにか開いてバックでもどると
ロックが解除されます。

一度アンインストールして、同じバージョンをインストールし直しましたが
起こりました。
https://youtu.be/-jv4YPnCu9Y
状況ムービー

**Comment by tkrworks** [comment]
クローズされず、放置されてるので、僕の方でクローズします。
