### ISSUE TITLE
「基本設定」項目が消える

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#91]
右上隅の歯車型のアイコンで、適当な項目を選択した後、再度アイコンをタップすると、一番上の「基本設定」が消えます。

機種 : Xperia Z3 SGP611（タブレット）, Xperia Z3 SO-02G（スマホ）
OS : 両機種ともAndroid 6.0.1
アプリ : v0.8.3

**Comment by tkrworks** [comment]
症状、確認しました。

**Comment by ChihiroSuzuki** [comment]
一度「スキャン」すれば、「基本設定」は消えないようです。

**Comment by tkrworks** [comment]
症状確認し、修正しました。 https://github.com/jins-meme/JinsMemeBRIDGE-Android/commit/5bc8d8dcf64f356f32bed48d96439813674c25e4
次バージョンに反映させます。
