### ISSUE TITLE
「MIDI (for Eye VDJ)」設定に入れない。

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#92]
Androidの設定より、「開発者向けオプション」-「ネットワーク」-「USB設定の選択」を「MIDI」に変更しても、BRIDGEアプリの「MIDI (for Eye VDJ)」設定に入れません。PCとAndroid端末をUSB接続していても同様です。

機種 : Xperia Z3 SGP611（タブレット）
OS : Android 6.0.1
アプリ : v0.8.3

**Comment by tkrworks** [comment]
midiの設定がそこじゃないです。

画面最上部のステータスバーを下にスライドさせて出てくるusbの設定の方。

そちらで再度確認願います。

**Comment by ChihiroSuzuki** [comment]
設定画面に入れました。おさわがせしました。
