### ISSUE TITLE
フロント・リアでカメラ画面の大きさが異なる。

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#93]
BRIDGEアプリの「Camera」で写真を撮る際、内側のカメラ（自撮りできるほう）に切り替えた時、カメラ画面の横幅が少し狭くなります。

機種 : Xperia Z3 SGP611（タブレット）
OS : Android 6.0.1
アプリ : v0.8.3

**Comment by nariakiiwatani** [comment]
@ChihiroSuzuki 
使用しているカメラで撮影できる最大サイズのアスペクト比をプレビューに反映させているので、おそらくお使いの機種のカメラ仕様が影響していて、想定内の動作です。

@tkrworks 
バグっぽく見えるのであれば修正対象かと思いますが、対処どうしましょう？
カメラプレビューが乗っかる領域の背景を黒く塗りつぶしておくとかですかね？

**Comment by tkrworks** [comment]
@nariakiiwatani 
これは仕様と言うことにし、マニュアルに書いておけば良いことにしましょう！
