### ISSUE TITLE
アプリ復帰時、カメラが停止する

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#94]
「CAMERA」カードを選んだ状態で、BRIDGEアプリから抜け、復帰すると、カメラが停止したままになります。①スリープから復帰 ②他のアプリ以降から復帰 ③ホームボタンから復帰 いずれの場合も同様で、フロント・リアどちらのカメラでも起こります。

機種 : Xperia Z3 SGP611（タブレット）
OS : Android 6.0.1
アプリ : v0.8.3

**Comment by nariakiiwatani** [comment]
修正しました。
次バージョンでご確認お願いします。
