### ISSUE TITLE
カメラカード連打時の挙動

### ISSUE THREAD

**Issue by HulcMizoshita** [jins-meme/JinsMemeBRIDGE-Android#95]
カメラカードをシングルタッチするとTAKE A PICTUREボタンが出てきて写真をとれるようになりますが
連打した場合画面が薄暗くなり、TAKE A PICTUREボタンは押しても反応しない状態になりました。
戻るボタンやホームボタン、設定ボタンは正常に反応します。

機種：xperia z3 SO-02G
os：android6.0.1
アプリver：0.8.3

**Comment by nariakiiwatani** [comment]
@HulcMizoshita 
画面が薄暗くなり、ボタンの反応がなくなるのはポーズ機能の仕様ですので、何らかの操作がポーズ操作とご認識されたものだと思われます。
ちなみにポーズ操作はMeme操作では首を傾けたまま2.5秒、指操作では1秒の長押しです。

Memeを接続解除した状態で、再現性を報告していただけますでしょうか。
連打が必ずポーズを引き起こすのか、それとも連打は必須でなくて何らか特定のタイミングで発生するのかが知りたいので、何回トライ中の何回発生したのかもご報告ください。
よろしくお願いします。

**Comment by HulcMizoshita** [comment]
@nariakiiwatani 
どうやらカメラカードの連打が引き金ではなく、カメラのviewをタッチすることで発生するようです。
連打時もカメラのviewの位置を連打すると起こりますが、TAKE A PICTUREボタンの位置だと起こりません。
長押しではなく一瞬のタッチで起こります。
二十回トライして毎回再現できました。

**Comment by nariakiiwatani** [comment]
ありがとうございます。再現できました。調査します。

**Comment by nariakiiwatani** [comment]
修正しました。
次バージョンでご確認お願いします。
