### ISSUE TITLE
「基本設定」で全ての機能をオフにするとアプリが強制終了し、立ち上がらなくなる。

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#96]
「基本設定」-「機能の使用」で、CameraやSpotifyなど、全機能の使用をオフにし、設定画面を抜けようとすると、「問題が発生したため、[BRIDGE]を終了します。」というダイアログが出てBRIDGEが強制終了します。再度アプリを立ち上げようとしても同じダイアログが出てBRIDGEが起動しなくなります。
インストールし直すと、初回では同様のエラーで起動してくれないのですが、2回目以降は起動してくれます。

機種 : Xperia Z3 SGP611（タブレット）
OS : Android 6.0.1
アプリ : v0.8.3

**Comment by tkrworks** [comment]
少なくとも1機能はオンで、全てをオフにできない仕様にします。

**Comment by tkrworks** [comment]
次のバージョンにて反映します。
