### ISSUE TITLE
Hue Bridgeの探索が止まらない。

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#97]
「Philips Hue」設定で、「Hue Bridge接続・認証エラー」が出た後、再び接続しようとすると、探索が止まらず、操作できなくなります。一度、設定画面を抜けても同様のようです。

機種 : Xperia Z3 SGP611（タブレット）
OS : Android 6.0.1
アプリ : v0.8.3

**Comment by tkrworks** [comment]
「Hue Bridge接続・認証エラー」を出す手順も教えて下さい。

**Comment by ChihiroSuzuki** [comment]
Philips Hue が無い状態で接続しようとすると出ます。

**Comment by tkrworks** [comment]
Hue Bridgeはあるけど、Hueがないということですか？

**Comment by ChihiroSuzuki** [comment]
Hue Bridge も無い状態です。

**Comment by tkrworks** [comment]
了解です。

**Comment by tkrworks** [comment]
症状確認しました。

**Comment by tkrworks** [comment]
次バージョンにて反映します。
