### ISSUE TITLE
オフライン時でのSpotifyログインの挙動

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#98]
オフライン時に「Spotify」設定より「ログイン認証」しようとすると、一瞬画面が暗転するだけで、エラーダイアログ等の表示がありません。また、ログインするときにタップするボタンがアクティブになったままです。

機種 : Xperia Z3 SGP611（タブレット）
OS : Android 6.0.1
アプリ : v0.8.3

**Comment by tkrworks** [comment]
「オフライン時」

という状態を具体的に教えて下さい。

**Comment by ChihiroSuzuki** [comment]
Wifiに接続せず、Android端末をスタンドアロンにしている状態です。

**Comment by tkrworks** [comment]
了解です。
