### ISSUE TITLE
カメラモードから戻ろうとするとアプリが落ちる

### ISSUE THREAD

**Issue by ChihiroSuzuki** [jins-meme/JinsMemeBRIDGE-Android#99]
カメラのカードをタップし、カメラがアクティブになる時、カメラ画面が黒く表示される時間があると思うのですが、その黒い画面が出るのと同じタイミングで前画面に戻ろうとするとアプリが落ちます。
それより前後のタイミングだと落ちないようです。

機種 : Xperia Z3 SGP611（タブレット）
OS : Android 6.0.1
アプリ : v0.8.3

**Comment by nariakiiwatani** [comment]
修正しました。
次バージョンでご確認ください。
